[package]
name        = "kopparoxid-term"
version     = "0.0.1"
description = "Terminal simulation and control-seuence management"

[lib]

[dependencies]
bitflags = "0.5.0"
chomp    = "0.2.0"
log      = "0.3.0"
